- name: Run GitHub Metrics action
  uses: lowlighter/metrics@latest
  with:
    filename: 'metrics_renders/github-metrics.svg'
    base: 'base'
    extras_css: |
      .main { fill: #ff69b4 !important; }
      .bar { fill: #ff1493 !important; }
    github_token: ${{ secrets.GH_TOKEN }}
